let marks=[28.92,37,45,false,"Not Present"];
console.log(marks[0]);
console.log(marks[1]);
console.log(marks[2]);
console.log(marks[3]);
console.log(marks[4]);
marks[12]=6;
console.log(marks);
console.log(marks.length);
let num=[1,2,3,4,5  ];
let b= num.toString();
console.log(b);
console.log(typeof(b));  
let c=num.join("-");
console.log(c),typeof(c);
num.pop();
console.log(num);
num.push(78);
console.log(num);
let n=num.shift();
console.log(n);
num.unshift(45);
console.log(num);
